hacktech_gnar_car:
    resource: "@HacktechGnarCarBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

hello:
    path:     /hello/{name}
    defaults: { _controller: HacktechGnarCarBundle:Default:index }

sign_in:
    path:     /sign_in/
    defaults: { _controller: HacktechGnarCarBundle:Default:login }

results:
    path:     /results/
    defaults { _controller: HacktechGnarCarBundle:Default:search }

join_car:
    path:     /join_car/
    defaults { _controller: HacktechGnarCarBundle:Default:form }