parameters:
#    hacktech_gnar_car.example.class: Hacktech\GnarCarBundle\Example

services:
#    hacktech_gnar_car.example:
#        class: %hacktech_gnar_car.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
